### ISSUE TITLE
Suggest private vars when using var-quote?

### ISSUE THREAD

**Issue by vemv** [alexander-yakushev/compliment#101]
Compliment's lack of completions for private vars is desirable.

However when the symbol is preceded by `#'`, it's more reasonable to offer private vars as completions.

There are in fact codebases where the 'idiomatic' thing for private functions is to write tests like this: `(is (= 42 (#'sut/foo ,,,))`.

Any thoughts?

cc/ @eval who also worked on this area recently.

**Comment by alexander-yakushev** [comment]
Pretty sure it already works like that after @eval changes: https://github.com/alexander-yakushev/compliment/blob/master/test/compliment/sources/t_ns_mappings.clj#L111
