### ISSUE TITLE
String literals aren't inferred as strings

### ISSUE THREAD

**Issue by vemv** [alexander-yakushev/compliment#106]
Although it's very much a marginal case, I noticed that `(.| "a string")` doesn't trigger accurate completions.

If fixing it, one could also tackle other literals such as `[]` (admittedly interop on a vector is also a very marginal use case)

I'd be willing to work on this one.

**Comment by alexander-yakushev** [comment]
I'd say having that for a string literal is fine, but everything else is a stretch:).

**Comment by alexander-yakushev** [comment]
> Being able to invoke e.g. (.indexOf [3] 3) is kinda useful though.

What for? :) You already know that the index is 0.

**Comment by vemv** [comment]
Maybe I want to quickly remember the methods I can call on a vector 👀 and then remove `[]` with `my-vec`.

Sort of a contrived technique, however it's definitely quicker than any alternative I can think of.

**Comment by alexander-yakushev** [comment]
`[]` -> `cider-inspect` -> Click on the class name. Or `PersistentV` -> `Tab` -> `cider-inspect`. You get a buffer that doesn't go away so easily and is convenient to search, and you see all arities immediately.

**Comment by vemv** [comment]
Yeah but neither of those are as fast - with this approach it's about 3 keystrokes away (`[`, `.`, `tab`)

Another point of view is simply pride - when one sees a gazillion unrelated completions for `(.| [,,,)` , one just knows we can do better.

Either way, it's no big deal although probably I'd enjoy working on it some day.
