### ISSUE TITLE
Give `some->`/`some->>` similar treatment than that of `->`/`->>`

### ISSUE THREAD

**Issue by vemv** [alexander-yakushev/compliment#109]
As some context (and good news), `->` has kept working for me, in this case honoring `^String` metadata specified in a less obvious place:

<img width="591" alt="image" src="https://github.com/alexander-yakushev/compliment/assets/1162994/ead2ddd4-dcbc-40b5-b7d8-0c3e975148ef">

Now, I realised this doesn't work for `some->` and `some->>`.

Should be a pretty easy PR (if you don't wish to beat me to it).

Cheers - V

**Comment by alexander-yakushev** [comment]
Go ahead, would gladly merge it

**Comment by vemv** [comment]
I've tested the snapshot out for a few days and it works as intended - a release would be appreciated.
