### ISSUE TITLE
Interest in cljs-ish completions?

### ISSUE THREAD

**Issue by JJ-Atkinson** [alexander-yakushev/compliment#115]
I've noticed that compliment seems to barf context when there's a `clj(s)` reader tag in the context. i.e. `(def a [] #?(:cljs __prefix__))` always has a `nil` context. I'd be happy to try and fix this if there's interest, probably by just chucking the other branch of the reader tag. i.e. if you are editing the `clj` side of a reader only resolve that side in context.

**Comment by alexander-yakushev** [comment]
Hello! I think the problem comes from the fact that we don't pass `{:read-cond :allow}` to `read-string` when the context is parsed. I welcome a PR that fixes that.

**Comment by JJ-Atkinson** [comment]
#116
