### ISSUE TITLE
Determining if the prefix is being called within a given function/macro

### ISSUE THREAD

**Issue by vemv** [alexander-yakushev/compliment#119]
For https://github.com/clojure-emacs/cider-nrepl/pull/863#discussion_r1546019305 , I'd need to know if the prefix is being called within a given function macro, given a context.

e.g. "is `__prefix__` within a `future` call"?

That would be true here:

```clj
(future
  __prefix__)

(future
  (foo __prefix__))
```

But not here:

```clj
(do
  (future 42)
  (foo __prefix__))
```

...I'm wondering if this is something you've solved before, or that might be easy with some existing Compliment primitives?

Cheers - V

**Comment by vemv** [comment]
Any thoughts on this one?

The way I'd implement it would be probably by repatedly going `up` zippers.

**Comment by alexander-yakushev** [comment]
This should be possible without having to use zippers. The context format that Compliment provides is suitable for that. See https://github.com/alexander-yakushev/compliment/wiki/Context.
