### ISSUE TITLE
Completion candidates feature inner classes and anonymous inner classes

### ISSUE THREAD

**Issue by bbatsov** [alexander-yakushev/compliment#18]
![screen shot 2014-10-31 at 11 02 01 pm](https://cloud.githubusercontent.com/assets/103882/4868539/3cdaee1c-6141-11e4-881f-39140af7c866.png)

I don't think Java IDEs normally show those.

**Comment by DogLooksGood** [comment]
A lot of Java libraries use inner class, (e.g. `XXX.Bulider`), hide these candidate all the time is not a good solution for this case.

IntelliJ and Eclipse will show inner class when type something like
```java
XXX.B|
     |-> Builder
```
It will be better If `completion` provide inner class in this case:
```clojure
(XXX$B|
      |-> XXX$Builder
```
or something like this.
