### ISSUE TITLE
Special forms have no :ns tag

### ISSUE THREAD

**Issue by cichli** [alexander-yakushev/compliment#23]
```clojure
user> (->> (compliment.core/completions "" {:tag-candidates true})
           (filter #(= (:type %) :special-form)))
({:type :special-form, :candidate "do"}
 {:type :special-form, :candidate "if"}
 {:type :special-form, :candidate "def"}
 {:type :special-form, :candidate "new"}
 {:type :special-form, :candidate "try"}
 {:type :special-form, :candidate "var"}
 {:type :special-form, :candidate "set!"}
 {:type :special-form, :candidate "catch"}
 {:type :special-form, :candidate "quote"}
 {:type :special-form, :candidate "recur"}
 {:type :special-form, :candidate "throw"}
 {:type :special-form, :candidate "monitor-exit"}
 {:type :special-form, :candidate "monitor-enter"})
user> 
```

Should these have an `:ns` of `clojure.core`? Technically, you can't invoke any of them with a namespace prefix (i.e. `(clojure.core/try 1)` does not work), but I think they're generally considered to belong to that namespace.

Just pointing it out, in case you consider it an omission. I have no opinion either way :-).

**Comment by alexander-yakushev** [comment]
No, I don't think so. Special forms are special because they are defined in clojure.lang.Compiler, not in clojure.core. Namespace doesn't make sense for them.

**Comment by cichli** [comment]
> Special forms are special because they are defined in clojure.lang.Compiler, not in clojure.core

Of course. I only ask as it seems ambiguous to me as to whether they should be considered to be, in a sense, part of core. For example they're included in the API documentation for `clojure.core`: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/do - but maybe that's just because there isn't any other sensible place in the API docs for them to go :-).

**Comment by alexander-yakushev** [comment]
clojure.core has many weird things because of the limited runtime, and explicit attaching docs is one of them. Anyway I don't see how pretending that special forms belong to a namespace achieves anything. after all, Frontend can decide to attach clojure. core ns to a special form if it wants to.

**Comment by cichli** [comment]
Yeah, that definitely makes sense. I considered the frontend doing it - `cljs.core` complicates this as the frontend generally doesn't know if it's dealing with Clojure or ClojureScript - but as you say, it doesn't really achieve anything. Thanks for considering regardless.

**Comment by alexander-yakushev** [comment]
No problem. If there are technical reasons for doing this (compatibility, etc.), tell me and I will change the current behavior.
