### ISSUE TITLE
Resource completion

### ISSUE THREAD

**Issue by bbatsov** [alexander-yakushev/compliment#24]
It'd be nice if there was a source for resource completions. Those completions should be contextual - e.g. triggered only in functions known to accept resource paths. 

We can also reuse this functionality to implement `find resource` functionality in CIDER.

Related ticket https://github.com/clojure-emacs/cider/issues/1062

**Comment by alexander-yakushev** [comment]
Can you give more details what should that be? Should it complete paths inside strings or what exactly?

**Comment by bbatsov** [comment]
Yeah, my idea was it should complete paths in strings. Imagine:

```
(resource "prefix|")
```

You'd get all the resource names starting with prefix.

**Comment by alexander-yakushev** [comment]
Should it complete one directory at a time (like hippie-expand does), or the candidates should be full resource names right from the beginning?

**Comment by bbatsov** [comment]
Hmm, I was thinking about full resource paths (as it's easier to reuse those in ido).

**Comment by alexander-yakushev** [comment]
Wait, is there even a way to get all resources on classloader? The answers I found so far are very contrived.

**Comment by bbatsov** [comment]
No idea. Haven't really research the matter - I just assumed something like this should be possible.

**Comment by bbatsov** [comment]
Another concern is do we want to show all resources (e.g. in jars), or just the ones that are actually in the current project.

**Comment by alexander-yakushev** [comment]
It it. There seem to be a lot of resources in Java itself, don't know how useful are those.

**Comment by bbatsov** [comment]
Ok, let's just show the ones in the project.

**Comment by alexander-yakushev** [comment]
One more thing: by default AC does not initiate completion if it starts inside a string. What about company-mode?

**Comment by bbatsov** [comment]
company-mode does completions inside strings out of the box.

On 20 April 2015 at 12:39, Alexander Yakushev <notifications@github.com>
wrote:

> One more thing: by default AC does not initiate completion if it starts
> inside a string. What about company-mode?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexander-yakushev/compliment/issues/24#issuecomment-94408836>
> .
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by alexander-yakushev** [comment]
Done, please see my comment in clojure-emacs/cider#1062

**Comment by bbatsov** [comment]
```
user> (compliment.sources.resources/resources-by-prefix "")
("meta-index" "META-INF/maven/cider/cider-nrepl/pom.properties")
```
This doesn't look totally right. I can find a file called `meta-index` and `pom.properties` is in the target directory of the lein project.

**Comment by bbatsov** [comment]
@alexander-yakushev ping

**Comment by alexander-yakushev** [comment]
> This doesn't look totally right. I can find a file called meta-index and pom.properties is in the target directory of the lein project.

Still this is considered as project resources by the way they look on the classpath. We can remove them two specifically, but who cares? Besides it is easier to test this functionality when you have them. Otherwise Compliment has no other resources.

**Comment by bbatsov** [comment]
OK

On 25 April 2015 at 18:13, Alexander Yakushev <notifications@github.com>
wrote:

> This doesn't look totally right. I can find a file called meta-index and
> pom.properties is in the target directory of the lein project.
>
> Still this is considered as project resources by the way they look on the
> classpath. We can remove them two specifically, but who cares? Besides it
> is easier to test this functionality when you have them. Otherwise
> Compliment has no other resources.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexander-yakushev/compliment/issues/24#issuecomment-96220637>
> .
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com
