### ISSUE TITLE
0.2.2-SNAPSHOT is not deployed to clojars

### ISSUE THREAD

**Issue by bbatsov** [alexander-yakushev/compliment#25]
See https://clojars.org/compliment

**Comment by alexander-yakushev** [comment]
The latest dev version is `0.2.1-SNAPSHOT` but I will deploy a new one once I implement the resource patch.

**Comment by bbatsov** [comment]
I see 3 commits after https://github.com/alexander-yakushev/compliment/commit/8b36b06684cbd8d00e9a2c9af006b131284023ba

**Comment by alexander-yakushev** [comment]
I told you on IRC that I pushed changes as 0.2.1-SNAPSHOT so that you didn't have to update cider's project.clj again. Anyway, wait for just couple of minutes more, it's coming through:).

**Comment by bbatsov** [comment]
Ah, I totally forgot about this. Sorry.

**Comment by alexander-yakushev** [comment]
No problem, it was a malpractice by me to do that in the first place.

**Comment by alexander-yakushev** [comment]
0.2.2-SNAPSHOT is now pushed, sorry for the confusion.
