### ISSUE TITLE
Does not provide completions for :let-bound vars

### ISSUE THREAD

**Issue by expez** [alexander-yakushev/compliment#31]
In `doseq` and `for` you can use `:let` to create new bindings.  Afaict compliment isn't aware of this context.

**Comment by alexander-yakushev** [comment]
I can do that. Coming soon.

**Comment by alexander-yakushev** [comment]
Pushed in `0.2.4-SNAPSHOT`.

**Comment by expez** [comment]
7 hour response time; incredible! :+1:

**Comment by alexander-yakushev** [comment]
I could do better if I weren't swamped with classloader voodoo in another project :stuck_out_tongue_winking_eye:
