### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by EwenG** [alexander-yakushev/compliment#32]
Hi,
I'm currently writing an emacs mode for clojure development. I would love to embed compliment in order to provide auto completion, though I can't because of GPL/EPL license incompatibility. Would you consider dual licensing with a GPL compatible license?

**Comment by alexander-yakushev** [comment]
I don't mind it. What exactly should I do to dual-license?

**Comment by bbatsov** [comment]
You're going to embed in into something that's under GPL? CIDER's Emacs part is licensed under GPL and the Clojure part is under EPL, which is a fine arrangement IMO. You won't get a dual-licensed Clojure after all...

**Comment by EwenG** [comment]
Cider is not distributed with any clojure source file, is it?

Concerning the Clojure compiler and clojure.core, the way I understand the GPL is that it includes exceptions about languages and standard interfaces, which I think clojure.core is.

**Comment by EwenG** [comment]
@alexander-yakushev You would need to choose a license, and then ask all contributors of compliment if they are ok to change the license of the project (or add a new one if dual licensing).

**Comment by alexander-yakushev** [comment]
Meh... I think @bbatsov is right, you won't get far with GPL and Clojure since all the other libraries are under EPL. Compliment depends on some other things too, and those are under EPL.

Is there any other way?

**Comment by bbatsov** [comment]
Probably some would disagree with me, but most likely no one will care about a minor license violation in an Emacs extension.

**Comment by EwenG** [comment]
I don't need midje, criterium or cloverage to run compliment. And I can get around defprecated by a few changes to the source code. Does compliment depends on something else?
It's true that many clojure libraries are EPL, but compliment is special since it is mainly targeted at writing tooling stuff.

**Comment by ReneFroger** [comment]
@bbatsov. Oh yes, one does care.. RMS. ;-).

**Comment by alexander-yakushev** [comment]
After thinking a little bit, I decided that I don't want to go the rabbit hole of dual-licensing the project, I don't know the implications of doing that and I don't have enough time to figure it out. Compliment stays the same license as Clojure.

Maybe you would be better download the Compliment dependency (together with all other dependencies) from Maven? Clojure is too closely tied to Maven, so you can't really avoid it — thus it doesn't make a lot of sense to embed something if you can download it on spot.

Also, you should really take a close look on `cider-nrepl` — it has a lot of goodies for IDE-related actions already written, and it's editor-independent. Doesn't make sense to redo all of those.

**Comment by EwenG** [comment]
OK no problem. I understand your choice.
