### ISSUE TITLE
Include boolean literals "true" and "false" in completion results

### ISSUE THREAD

**Issue by sanjayl** [alexander-yakushev/compliment#34]
Hi,
I've been using compliment via company-mode in cider, and I keep running into an issue where typing a boolean literal autocompletes to the associated predicate function (`true?` instead of `true` / `false?` instead of `false`). If you add the strings `"true"` and `"false"` to the `special-forms` set in `compliment.sources.special-forms`, then this problem goes away.

Thanks for the great package!
Sanjay

**Comment by alexander-yakushev** [comment]
Done. Thanks for the suggestion!
