### ISSUE TITLE
Prefixes for namespaces in namespaced keywords don't have completion candidates

### ISSUE THREAD

**Issue by expez** [alexander-yakushev/compliment#37]
If I do `::my-ns-alias/` then keywords in `my-ns-alias` are listed correctly, but the there's no completion suggestion while I'm typing `::my-ns-alias`

**Comment by alexander-yakushev** [comment]
Do you mean there is no completion here `my-ns-al█`?

**Comment by expez** [comment]
I've updated the OP slightly, I realize it was a bit unclear and I'm sorry about that.  I filed it quicky while hacking on something else :p 

Here's a more concrete example:

core.clj:

```
(ns test.core)

(def my-keywords #{::foo ::bar ::baz})
```

other.clj:

```
(ns test.other
  (:require [test.core :as my-ns-alias]))

(println ::my-ns-a|)
```

At the `|` there are no listed candidates, but I expected `::my-ns-alias` to be listed.  Once I write some more and and get to the slash (`::my-ns-alias/`) the completions work as expected and `foo` `bar` and `baz` show up.

**Comment by alexander-yakushev** [comment]
I see. Yes, I don't support that yet. Perhaps, keywords need the same treatment as vars in this regard. I will try to abstract some code away and implement this.

**Comment by alexander-yakushev** [comment]
@expez Could you please take a look at the commit and say if it is what you wanted?

**Comment by expez** [comment]
Yes, this looks like what I wanted :+1:

**Comment by alexander-yakushev** [comment]
I guess this should be resolved now :).
