### ISSUE TITLE
Variables with colons aren't always completed

### ISSUE THREAD

**Issue by dpsutton** [alexander-yakushev/compliment#39]
I've written a failing test for you. This issue was raised on [CIDER](https://github.com/clojure-emacs/cider/issues/1709)

But vars with ~~semicolons~~ colons in them can be completed when the text doesn't include them. for instance, 

    (fact "handles vars with semicolons in them"
        (def foo:bar 1)
        (def foo:baz 2)
        (src/candidates "foo" *ns* nil)
        => (contains #{"foo:bar" "foo:baz"} :gaps-ok) ;; passes

        (src/candidates "foo:" *ns* nil)
        => (contains #{"foo:bar" "foo:baz"} :gaps-ok) ;; fails

        (src/candidates "foo:b" *ns* nil)
        => (contains #{"foo:bar" "foo:baz"} :gaps-ok)) ;; fails

**Comment by dpsutton** [comment]
oh and i put these in the t_ns_mappings.clj file. I wasn't sure of the etiquette of submitted a pull request with failing tests in it.

**Comment by alexander-yakushev** [comment]
First, `:` is a colon, `;` is a semicolon ;)

Colons in symbols are disabled here: https://github.com/alexander-yakushev/compliment/blob/master/src/compliment/sources/ns_mappings.clj#L10 . It seemed a reasonable exclusion at that time, but now I see that colons are officially legal parts of symbols (http://clojure.org/reference/reader#_symbols).

I will fix this soon. Thanks for the provided test cases!
