### ISSUE TITLE
Clojurescript support

### ISSUE THREAD

**Issue by EwenG** [alexander-yakushev/compliment#42]
Hi, I extended compliment to support clojurescript completion as part of [replique](https://github.com/EwenG/replique). Is that something you would be interested in ?

**Comment by alexander-yakushev** [comment]
Sure! It probably involves rewriting the code to `cljc` first, right?

**Comment by EwenG** [comment]
Not for my implementation because it does not support self-hosted clojurescript. It mainly involves unifying the clojure and clojurescript namespaces. See [here](https://github.com/EwenG/replique/blob/master/src/replique/environment.clj). Also, we need to reify the different kinds of environments (clojure and clojurescript). My implementation represents the clojure environment with nil and the clojurescript environment with replique.environment/ICljsCompilerEnv (because the clojurescript compiler env is just an atom and thus can't participate into polymorphism). I also added a parameter to all source functions to be able to pass the compiler env. This is a breaking change. I don't know how you would like to handle this.

**Comment by arichiardi** [comment]
It would be great to support both self-hosted and normal ClojureScript. Lumo [has already](https://github.com/anmonteiro/lumo/blob/master/src/cljs/snapshot/lumo/repl.cljs#L816-L962) a set of functions that complete, it would be really awesome to unify the api under `compliment`.

**Comment by alexander-yakushev** [comment]
Could someone please explain me the difference in writing a library for self-hosted ClojureScript vs not self-hosted? I have limited experience with CLJS, writing webpages and compiling it with ClojureScript compiler. cljc works there. Is self-hosted option different?

**Comment by EwenG** [comment]
Making compliment to support clojurescript would require to update compliment to understand the clojurescript compiler data (cljs namespaces, vars ...). This is what I have done in replique.

Making compliment to support self-hosted clojurescript would require to use the .cljc extension and to develop alternative implementations for jvm specific code (file system io, classpath ...)

**Comment by alexander-yakushev** [comment]
Is self-hosted CLJS implies it running only on Node.js/Nashorn/etc.?

**Comment by EwenG** [comment]
self hosted cljs would implies that some features are platform specific (only on node.js/nashorn/etc) and other features are not (those that do not rely on platform specific code)

**Comment by arichiardi** [comment]
Hello again guys, I was looking again at completion and specifically at [tern](http://ternjs.net/) for js support. This would be probably be one of the "completion" providers or middleware in a potentially extensible completion engine. I haven't looked at the code here yet, but I will.

**Comment by arichiardi** [comment]
Ok it was "source" lol

**Comment by arichiardi** [comment]
I basically wrote a (basic) layer on top of the cljs compiler state a while ago and, while probably not really complete, it could be reused: https://github.com/Lambda-X/replumb/blob/master/src/cljs/replumb/ast.cljs

**Comment by arichiardi** [comment]
Sorry to toss this here again but given the work I am doing [here](https://github.com/clojure-emacs/orchard/pull/37) while porting the info code from `cljs-tooling` to the `orchard`, I was thinking that it might make sense to more the completion code to `compliment.

The advantages would be multiple:

 * One consolidated API - the `compliment` one that most of the tooling understand 
 * One library to rule them all
 * One less library to include in `cider-nrepl`

I would be doing the work as I am doing it there, bringing all the tests over as well.
The code is not actually that complicated. The ClojureScript `*env*` is basically a giant map containing the compiler state.

If @alexander-yakushev is ok I will queue it next.

**Comment by alexander-yakushev** [comment]
Hey Andrea, I'm totally OK with Compliment supporting CLJS. I'm just the wrong person to do it because I don't use CLJS much to implement that properly, but if someone comes up with a PR I'd be happy to include it:)

**Comment by arichiardi** [comment]
This has been started #62

**Comment by arichiardi** [comment]
So at the moment there is a big `compliment.sources.cljs` namespace with all the sources for ClojureScript.

I saw that you have better separation in the Clojure side and I think at some point I should probably break down the different parts so that we can take advantage of the fuzzy matching.

For now though, this approach was the fastest and it works fine.

**Comment by bbatsov** [comment]
I think we can close this now that we decided this belongs in https://github.com/clojure-emacs/clj-suitable, which provides Compliment sources for ClojureScript completion.
