### ISSUE TITLE
Make context scanning more robust to unfinished forms

### ISSUE THREAD

**Issue by alexander-yakushev** [alexander-yakushev/compliment#53]
This should enable locals completion for those who don't use Paredit, inlcuding rebel-readline (see bhauman/rebel-readline#28).

**Comment by arichiardi** [comment]
My 2c, I like local let completions but the "dumb" word completion should not be part of this library but part of the editor. You risk duplicating things, for instance company-mode for Emacs already does that.

**Comment by alexander-yakushev** [comment]
Should be working now as of `0.3.9`.
