### ISSUE TITLE
core.typed integration?

### ISSUE THREAD

**Issue by cartesian-theatrics** [alexander-yakushev/compliment#54]
Is there any interest in using core.typed to drive completion? Particularly interesting would be to complete java interop forms:

```clojure
(.. "Hello World" toLow<tab>)
 ==> (.. "Hello World" toLowerCase)
```

The `cf` macro or something similar in core.typed could do a lot of the work here. It would seem you could go a long way with that and a bit of reflection. Of course, this would be jvm clojure only.

**Comment by alexander-yakushev** [comment]
Sorry, I never looked into this, and most probably never will. `core.typed` is a heavy dependency for something lightweight like Compliment.
