### ISSUE TITLE
Non static member completion not working?

### ISSUE THREAD

**Issue by didibus** [alexander-yakushev/compliment#57]
I can't seem to get non static member completion to work. If I do the following:

```
(def foo "test")
(.c foo)
```

I get all kind of completions unrelated to String, like `.checkSystemClipboardAccess`.

Same with this one:

```
(def bar (HashMap.))
(.p bar)
```

I expect to see only HashMap methods starting with p, as stated in the examples wiki: https://github.com/alexander-yakushev/compliment/wiki/Examples.

Regards

**Comment by behrica** [comment]
Same problem for me in emacs/cider

It never worked for me, but I was not aware so far, that it should work,,,

**Comment by alexander-yakushev** [comment]
@didibus Can you please describe your setup/versions? The `String` example works for me, but the HashMap one indeed doesn't if I don't import java.util.HashMap before.

**Comment by alexander-yakushev** [comment]
OK, I discovered a bug when even after importing HashMap its methods are still not shown. It's a mystery how this bug stood for so long.

I'm still interested in your setup to understand why String methods are not filtered, though.

**Comment by behrica** [comment]
I somehow think it is a Emacs/Cider related problem.
@didibus, are you sing Cider ?

I created this issue in Cider:
https://github.com/clojure-emacs/cider/issues/2528

**Comment by behrica** [comment]
Unrelated to emacs/cider.

It's an other problem.

I updated clojure-emacs/cider#2528 accordingly

**Comment by didibus** [comment]
I am using Cider. I won't have a computer till Wednesday, but I'll share my
setup details once I do.

Thanks.

**Comment by didibus** [comment]
So I'm running:

GNU Emacs 25.1.1 (x86_64-redhat-linux-gnu, X toolkit, Xaw3d scroll bars) of 2016-10-19
CIDER 0.19.0snapshot (package: 20181030.2222)
Spacemacs v.0.300.0

**Comment by alexander-yakushev** [comment]
Just to be on the safe side, please upgrade to the latest CIDER snapshot and try again. I fixed a related bug there. Also, do you mind sharing how your CIDER config looks like in `init.el`?

**Comment by alexander-yakushev** [comment]
Refreshing my memory on this, looks like this was an issue with CIDER and not so much with Compliment.
