### ISSUE TITLE
Leverage type hints?

### ISSUE THREAD

**Issue by vemv** [alexander-yakushev/compliment#60]
Hi!

For the following example:

```clojure
(defn thing [^String s]
  (. s|))
```

`|` being the cursor, ideally compliment would infer that `s` is a String, offering accurate completions accordingly.

(bonus points: also accurately complete at `(-> s .|)`)

My thinking is that type hinting could be a more extended practice if it resulted in accurate completions. Which would yield faster code and a more pleasant dev UX, so why not? :)

I assume the feature isn't there because I that's not the behavior I can observe (or find in https://github.com/alexander-yakushev/compliment/wiki/Examples).

Is this something you have attempted in the past? Or willing to give a shot someday?

I could try it myself. Would appreciate any info that might aid an implementation.

Cheers - Victor

**Comment by vemv** [comment]
Hmm, I cloned the repo, played with the code and actually checked that compliment already has some cool metadata parsing in place! My exact example gets the right completions.

However, in practice, i.e. in CIDER, the completions are much less precise.

Let me show you graphically:

![image](https://user-images.githubusercontent.com/1162994/53289012-7fc5d280-3790-11e9-94b1-1e4b73602753.png)

vs.

![image](https://user-images.githubusercontent.com/1162994/53289018-91a77580-3790-11e9-994a-44792c2f5bd9.png)

Do you get the same overly-broad completions in your environment?

It might be specific to CIDER, _my_ CIDER (I use a slightly old, slightly forked version), company-mode...

**Comment by alexander-yakushev** [comment]
Hi, thanks for the suggestion! Indeed, I've implemented this particular feature recently, in [0.3.8](https://github.com/alexander-yakushev/compliment/blob/master/CHANGELOG.md#038-2018-12-17). If you are using an older CIDER and more importantly cider-nrepl, then you are not getting the latest version of Compliment, and thus these features :).

**Comment by vemv** [comment]
Hey there,

awesome to know! Looking forward to upgrade asap.
