### ISSUE TITLE
Pass additional parameters to :candidates function

### ISSUE THREAD

**Issue by arichiardi** [alexander-yakushev/compliment#63]
Hi @alexander-yakushev I hope my #62 PR is not super scary but  I have a new requirement for the `:candidates` function that plugs in `defsource`: basically ClojureScript completions require the compiler map to be passed through all the functions, because that's where the information we need lives.

I was wondering how to manage that, because it could potentially be breaking.

What do you think? What should we do?

**Comment by alexander-yakushev** [comment]
Can you perhaps use a dynamic variable for that?

**Comment by arichiardi** [comment]
Yes I think I can :smile: Good idea!

**Comment by arichiardi** [comment]
Well actually `orchard`, or `cider-nrepl` already use that and I was hoping to pass things in `compliment.core`, which is good for testing, however changing the interface it's probably the worst possible choice here

**Comment by arichiardi** [comment]
Here is the call to `cljs-tooling`, for completeness - https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/complete.clj#L10-L20

**Comment by arichiardi** [comment]
I have a working version with a dynamic car but it hurts the eye a bit.

I would like to propose one change that would not be breaking:

`[... & option-map]` 

That way any source implementation can pass the key it desires.

What do you think?

**Comment by alexander-yakushev** [comment]
I would like to see first how the dynamic var implementation looks like. If it is really ugly, I'm fine with the extra optional argument.

**Comment by arichiardi** [comment]
Closing this because I am using a dynamic var in #62 now.
