### ISSUE TITLE
Have a way to filter out sources

### ISSUE THREAD

**Issue by arichiardi** [alexander-yakushev/compliment#68]
Hi @alexander-yakushev, I have discovered a possible issue in the way the sources are handled in `compliment`.

In `cider-nrepl` I added an attemptative implementation:

```clojure
(defn complete
  [{:keys [ns symbol context extra-metadata] :as msg}]
  (let [prefix (str symbol)
        options-map {:ns (misc/as-sym ns)
                     :context context
                     :extra-metadata (set (map keyword extra-metadata))}]
    (if-let [cljs-env (cljs/grab-cljs-env msg)]
      (binding [cljs-sources/*compiler-env* cljs-env]
        (complete/completions prefix (merge options-map {:sources [::cljs-sources/cljs-completions]})))
      (complete/completions prefix options-map))))
```

The problem is that given I have called `defsource` with the ClojureScript completions, now the sources are mixed up with the Clojure ones.

So I would need a way to exclude the ClojureScript completions in the `else` branch. Something like `:without-sources` could work.

I am also of course open to any other kind of solutions, if you have anything else in mind.

**Comment by bbatsov** [comment]
I guess alternatively there can be separate sources for each type (clj, cljs, clr, etc) and you'd just select the right ones by based on the type of completion you're doing.

**Comment by philomates** [comment]
related to this issue is https://github.com/alexander-yakushev/compliment/pull/88, where the list approach in https://github.com/arichiardi/compliment/commit/d6e7b40c892006178c1c25749351ecffd59bdf92 excludes the potential for user-defined sources to be considered in cider-nrepl completion suggestions

**Comment by alexander-yakushev** [comment]
I guess we have this now.
