### ISSUE TITLE
Autocomplete java methods from object returned from a deref?

### ISSUE THREAD

**Issue by didibus** [alexander-yakushev/compliment#73]
I'm not sure if this is possible, but given I a delay for example, which return a java object when running deref, is there anyway to type hint the delay's deref value or some other way so that compliment can auto-complete in a scenario as follows:

```
(def some-delayes-java-obj
  (delay (SomeObj.)))

(. <auto-complete here> @some-delayes-java-obj)
```

Regards

**Comment by alexander-yakushev** [comment]
Agree, can't do it reliably and generally, and overall not worth the trouble.

If you need that as an one-off thing, this should work:

```clj
(.| ^SomeObj @some-delays-java-obj)
```

And the hint would still be useful to prevent reflection.
