### ISSUE TITLE
Too many completions for Java objects

### ISSUE THREAD

**Issue by cjohansen** [alexander-yakushev/compliment#81]
When I try completions with my cursor on the pipe:

```clj
(.| (java.time.LocalDate/now))
```

I can find methods on `LocalDate`, among what seems to be every other method currently on my classpath. I would expect the list of completions to only include those available on the local date.

**Comment by bbatsov** [comment]
I'm not sure if there's much we can do here, as we don't really evaluate the receivers to figure out their exact type and narrow down the list of completions. Plus, most of the time you won't even have the receiver in place when doing `(.| ...)`.

**Comment by alexander-yakushev** [comment]
Yes, unfortunately, there is only so much we can do to figure out the class of the receiving object. Even in this example, that would involve too much (finding out the correct static method for the name and arity, it can have different return types based on the types of arguments, etc).
