### ISSUE TITLE
ns completions for cljc-files

### ISSUE THREAD

**Issue by eval** [alexander-yakushev/compliment#90]
It seems that cljc files are not considered by `compliment.utils/namespaces-on-classpath`.  

Hence the namespace [`malli.core`](https://github.com/metosin/malli/blob/master/src/malli/core.cljc) is not offered as a completion in the following example:
```clojure
$ clojure -Sdeps '{:deps {org.clojure/clojure {:mvn/version "RELEASE"} metosin/malli {:mvn/version "RELEASE"} compliment/compliment {:mvn/version "RELEASE"}}}' \
          -M -e '(prn ((requiring-resolve (quote compliment.core/completions)) "malli."))'
({:candidate "malli.dev", :type :namespace} {:candidate "malli.instrument", :type :namespace} {:candidate "malli.instrument.cljs", :type :namespace})
```

Let me know what you think and I'll submit a PR!

**Comment by alexander-yakushev** [comment]
Hello Gert! Thank you for pointing this out and for an exhaustive reproducer! I'll be more than glad to take a PR from you that fixes this.

**Comment by eval** [comment]
Hi Alexander, thanks for quick reply! Opened #91.
