### ISSUE TITLE
Doc of ns via alias

### ISSUE THREAD

**Issue by eval** [alexander-yakushev/compliment#93]
Is this something that we want to support?
```clojure
user=> (compliment.core/documentation "clojure.set")
"clojure.set\nSet operations such as union/intersection.\n"
user=> (require '[clojure.set :as cset])
nil
user=> (compliment.core/documentation "cset")
""
```

**Comment by eval** [comment]
I use compliment to enhance (the vendored) rebel-readline in [deps-try](https://github.com/eval/deps-try).  

But I also checked in CIDER, and thought it was not working but that was a jack-in using bb. Via clojure it works indeed.

**Comment by alexander-yakushev** [comment]
I don't see a reason why not. There could be some minor annoyances where the namespace alias matches one of the vars, and I think in that case the doc will contain both of them. But given that namespace docstrings are quite rare anyway, it shouldn't be a big problem. Looking forward to a PR!
